spring:
  cloud:
    gateway:
      enabled: true
      # 路由
      routes:
        ## system-server 服务
        - id: srb_service_route
          uri: lb://yikes-service
          predicates:
            - Path=/api/srbcore/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'